[package]
name = "sawtooth-raft"
version = "0.1.0"
authors = ["Intel Corporation"]

[dependencies]
clap = "2"
hex = "0.3"
log = "0.4"
protobuf = "2"
raft = "0.3.0"
sawtooth_sdk = { git = "https://github.com/hyperledger/sawtooth-core.git" }
serde_json = "1"
simple_logger = "0.5"
