version: '3.6'

volumes:
  cargo-registry:

services:
  raft-engine:
    image: sawtooth-raft-engine:$ISOLATION_ID
    build:
      context: .
    volumes:
      - .:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "
